app.environment=TEST

user-service.connect-timeout-ms=1000
user-service.read-timeout-ms=1000
payment-service.connect-timeout-ms=1000
payment-service.read-timeout-ms=1000

resilience4j.retry.instances.paymentService.max-attempts=5
