spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${backend.user-service.url}
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: ${backend.order-service.url}
          predicates:
            - Path=/api/orders/**
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

server:
  port: 8080

backend:
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8082
